config/routes.rb
Rails.application.routes.draw do
  resources :genres

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: [ :create, :destroy ]
  end

  resource :session, only: [ :new, :create, :destroy ]

  resources :users

  get "signin" =>"sessions#new"
  
  get "signup" =>"users#new"
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug
  validates :name, presence: true, uniqueness: true
  validates :slug, uniqueness: true
  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations


  def to_param
    slug
  end

  private

  def set_slug
    self.slug=name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_admin, except: [ :show, :index ]
  before_action :set_genre, only: [ :edit, :show, :update, :destroy ]


  def index
    @genres = Genre.all
  end

  def show
    @movies = @genre.movies.order(:title)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre created!"
    else
      flash.now[:alert] = "Genre Uncessufully created."
      render :new, status: :unprocessable_entity
    end
  end

  def edit ; end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated"
    else
      flash.now[:alert] = "Genre Unccessfully updated"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, status: :see_other, notice: "Genre successfully deleted!"
  end

  private
    def genre_params
      params.require(:genre).permit(:name)
    end

    def set_genre
      @genre = Genre.find_by!(slug: params[:id])
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model:@genre) do |form| %>
  <%= form.label :Name %>
  <%= form.text_field :name %>

  <%= form.submit(@genre.persisted?  ? "Update Genre" : "Create Genre") %>
  <%end%>

app/views/genres/edit.html.erb
<h1>Editing <%=@genre.name%> </h1>
<%= render  "form", genre: @genre %>

app/views/genres/index.html.erb
<div>
  <% if @genres.present? %>
    <h4>Genres</h4>
    <ul>
      <% @genres.each do |g| %>
        <li><%= link_to g.name, g%></li>
      <% end %>
    </ul>
  <% end %>
</div>
<% if current_user_admin? %>
  <section class="admin">
  <%= link_to "Create a genre", new_genre_path, class: "button"%>
  </section
<% end %>

app/views/genres/new.html.erb
<%= render "shared/errors", object: @genre %>
<h1> New Genre </h1>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<% if @movies.present? %>
  <ul> 
    <h2> <%= "#{@genre.name}'s movies" %> </h2>
    <% @movies.each do |m| %>
      <li><%= link_to m.title, m) %> </li>
    <% end %>
  </ul>
<% else %>
  <p> No movies in this genre yet. </p>
<% end%>

<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_genre_path, class: "button"%>
      <%= 
        link_to "Delete",
        genre_path, class: "button",
        data:{ turbo_method: :delete, turbo_confirm: "Sure?"} 
      %>
  </section
<% end %>